#  Template Java Gradle build

#  This template allows you to test and build your Java project with Gradle.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: appropriate project structure should exist in the repository.

image: atlassian/default-image:2

pipelines:
  default:
      - step:
          name : Send to GitHub
          script:
            - git remote add sync git@github.com:cemahi/first-pipeline-project3.git
            - git fetch
            - git checkout master
            - git pull    
            - git fetch sync master
            - git push -f sync master
      - step:
          name: Message to Slack
          script:
          - pipe: atlassian/slack-notify:2.0.0
            variables:
              WEBHOOK_URL: $WEBHOOK_URL
              MESSAGE: 'Hello, world!'
#      - step:
#          name: Build and Test
#          caches:
#            - gradle
#          script:
#            - ./gradlew clean
#            - ./gradlew build
#          after-script:
#            - pipe: atlassian/checkstyle-report:0.3.0
#      - step:
#          name: Security Scan
#          script:
#            # Run a security scan for sensitive data.
#            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
#            - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          name: Sonar Scan
          script:
            - pipe: ./gradlew build sonarqube

clone:
  depth: full    # SonarCloud scanner needs the full history to assign issues properly